### ISSUE TITLE
Error executing bayzee.generate

### ISSUE THREAD

**Issue by jtfogarty** [pandastrike/bayzee#1]
I'm attempting to use this engine against presidential speeches. I'm able to run dispatchToAnnotate, annotate and dispatchToGenerate but when I run generate, I get the below error;

NotFoundError: TransportError(404, u'{"_index":"obama__annotated","_type":"speeches","_id":"obama_speech-4427","found":false}')

Looking in Kibana I see items like the below with an _id = right-more-than ;

{"phrase":"right more than","document_id":"obama_speech-4427","phrase__not_analyzed":"right more than"}

Should this code be looking for document_id rather than _id ?  

Thanks

**Comment by maheshyellai** [comment]
@jtfogarty did you run annotation dispatcher and annotation worker as mentioned [here](https://github.com/pandastrike/bayzee#run)? Did that run succeed? You can check the annotated phrases and their features in `obama__annotated` index. It might help if you could paste the config file?

**Comment by jtfogarty** [comment]
Here is my config;

# Elasticsearch server

elasticsearch: 
  # host where Elasticsearch server is running
  host: "127.0.0.1"
  # port on which Elasticsearch server is listening
  port: 9200

#redis storage
redis:
  host: "127.0.0.1"
  port: 6379

# Corpus to use

corpus:
  # name of the Elasticsearch index where the corpus is stored
  index: "obama"
  # name of the Elasticsearch document type where the corpus is stored
  type: "speeches"
  # list of document fields to generate phrases from
  text_fields: ["transcript"]

timeoutMonitorFrequency: 3600000

# number of documents to process at a time

processingPageSize: 10

# indicate whether to start annotating from scratch

annotateFromScratch: True

# indicate whether to generate shingles

indexPhrases: True

# indicate whether to generate postags

getPosTags: True

# Processors (add custom processors to list of modules)

processor:
  # name of the Elasticsearch index where annotated text is stored by the processors
  index: "obama__annotated"
  # name of the Elasticsearch document type where annotated text is stored by the processors
  type: "speeches"
  # list of processor modules
  modules:
      # standard bayzee processor to POS tag english text
      # name of the prcessor
    - name: "pos_processor"
      # path to the python module (relative to the location of this config file)
      path: "../lib/pos-processor.py"
      # features that this processor extracts
      features:
        - name: "pos_tags"
          isNumerical: False
        - name: "first_pos_tag"
          isNumerical: False
        - name: "middle_pos_tag"
          isNumerical: False
        - name: "last_pos_tag"
          isNumerical: False
        - name: "avg_word_length"
          isNumerical: True
        - name: "non_alpha_chars"
          isNumerical: True

# Generation

generator:
  # training set file path (relative to the location of this config file)
  trainingPhrasesFilePath: "training-phrases.csv"
  # hold-out set file path (relative to the location of this config file)
  holdOutPhrasesFilePath: "hold-out-phrases.csv"
  # maximum number of words in generated phrase
  maxShingleSize: 3
  # minimum number of words in generated phrase
  minShingleSize: 2
  # list of features to extract
  features:
    - name: "doc_count"
      isNumerical: True
    - name: "max_term_frequency"
      isNumerical: True
    - name: "avg_term_frequency"
      isNumerical: True
    - name: "max_score"
      isNumerical: True
    - name: "avg_score"
      isNumerical: True
  # precision of numerical features
  floatPrecision: 4

# logger config

logger:
  # directory where log files are written (relative to the location of this config file)
  logsDir: "../logs"

**Comment by jtfogarty** [comment]
To answer your question complete, yes I ran dispatch -a, worker -a then dispatch -g, worker -g

here is a screenshot of the indexes in ES

![screen shot 2015-05-13 at 6 51 11 am](https://cloud.githubusercontent.com/assets/6708730/7609836/db044582-f93c-11e4-9a19-86895f57fe2a.png)

Thanks for your help.

**Comment by maheshyellai** [comment]
@jtfogarty which version of Elasticsearch are you using?

**Comment by jtfogarty** [comment]
@maheshyellai 
Version: 1.4.4, Build: c88f77f/2015-02-19T13:05:36Z, JVM: 1.8.0_40

If you'd like to try with my data, the below link is to an IPython Notebook that loads ES.

https://github.com/jtfogarty/Elasticsearch-IPython-Notebook/blob/master/Presidential%20Speeches%20to%20ES.ipynb

**Comment by maheshyellai** [comment]
@jtfogarty sorry for not being able to respond earlier, was in the middle of a product release. I think the issue is with the version of Elasticsearch. We haven't tested bayzee on 1.4.4. I have upgraded Elasticsearch on my dev box. I will try to reproduce the issue and get back to you.

**Comment by maheshyellai** [comment]
@jtfogarty after upgrading to 1.4.4 version of Elasticsearch, I am still unable to reproduce the issue. Annotation and generation succeed for the speeches from Miller Center. 

Its possible we are using different elasticsearch client packages. We are running with 1.0.0. version of [elasticsearch package](https://pypi.python.org/pypi/elasticsearch). You can check the version of this client lib by running this command: `pip freeze | grep elasticsearch`.
If you are running a different version (even if later than 1.0.0), can you try installing 1.0.0 version of elasticsearch client package and run generation?

**Comment by jtfogarty** [comment]
I reinstalled on a fresh box.  No more errors.

Thanks for your help
